
var nom="TF, english 1, boxes p197";
var description="";

var quiz=[
    ["Assessment","Estimation"],
    ["Ability","Capacité"],
    ["Mixed child","Enfant métis"],
    ["Assumption","Supposition"],
    ["Embedded","Incrusté"],
    ["Psyche","Esprit"],
    ["Cross-section","Echantillon"],
    ["A bunch","Un groupe"],
    ["Trade-Unionists","Syndicalistes"],
    ["Those folks","Ces gens"],
    ["Jello-Mold","Gateau à la gelée de fruit"],
    ["Mantelpiece","Rebord de cheminée"],
    ["To disarm","désarmer"],
    ["To figure out ways of/to","Imaginer des facons de"],
    ["Trapped","Piégé"],
    ["Strength","Force"],
    ["Soulfulness","Capacité à s'exprimer avec son âme"],
    ["Defiant","Méfiant"],
    ["Common ground","Terrain d'entente"],
    ["Community","Communauté"],
    ["Identity","Identité"],
    ["Leader","Chef"],
    ["Network","Réseau"],
    ["Values","Valeurs"],
    ["To share","Partager"],
    ["To pay tribute to","Rendre hommage à"],
    ["An icon","Une icone"],
    ["A figure","Une figure"],
    ["To celebrate","Célébrer"],
    ["Commemorate","Commémorer"],
    ["To embody","Incarner"],
    ["To symbolize","Symboliser"],
    ["To fight for","Se battre pour"],
    ["To fight against","Se battre contre"],
    ["To raise awareness about","Sensibiliser à"],
    ["To speak up","Parler pour"],
    ["To speak against","Parler contre"],
    ["To stand up for","Se lever pour"],
    ["To stand one's ground","Tenir bon"],
    ["To take a knee","S'agenouiller"],
    ["An activist","Un activiste"],
    ["An advocate","Un avocat"],
    ["To demonstrate","Manifester"],
    ["To oppose","S'opposer"],
    ["To protest against","Protester contre"],
    ["Commited","Engagé"],
    ["Respected","Respecté"],
    ["To be involved in","Etre investi dans"],
    ["Diversity","Diversité"],
    ["Equality","Egalité"],
    ["Inclusion","Inclusion"],
    ["Influence","Influence"],
    ["To be discriminated against","Etre victime de discrimination"],
    ["To be looked down on","Etre méprisé"],
    ["Injustice","Injustice"],
    ["Stigmatization","Stigmatisation"],
    ["Stereotype","Stéréotype"],
    ["To be mistreated","Etre maltraité"],
    ["To demean","Rabaisser"],
    ["To humiliate","Humilier"],
    ["To harass","Harceler"],
    ["To persecute","Persécuter"],
    ["Fair","Juste"],
    ["Free","Libre"],
    ["Civil Rights","Droits civils"],
    ["Equal traitment","Traitement égal"],
    ["On an equal footing","Sur pied d'égalité"],
    ["To obtain equal rights","Obtenir des droits égaux"],
    ["Social justice","Justice sociale"],
    ["An achievment","Un accomplissement"],
    ["A challenge","Un défi"],
    ["Emancipation","Emancipation"],
    ["Fulfillment","Accomplissement"],
    ["The progress","Le progrès"],
];