
var nom="verbes espagnols";
var description="";

var sens=["esp","fr"]

//í á ñ À

var quiz=[
    ["ser","être"],
    ["estar",["être","se trouver"]],
    [["tener","haber"],"avoir"],
    ["hacer","faire"],
    ["ver","voir"],
    ["mirar","regarder"],
    ["vivir",["vivre","habiter"]],
    ["comer","manger"],
    ["beber","boire"],
    ["poder","pouvoir"],
    ["querer",["vouloir","aimer"]],
    ["trabajar","travailler"],
    ["leer","lire"],
    ["oir","entendre"],
    ["escuchar","écouter"],
    [["pedir","preguntar"],"demander"],
    ["contestar","répondre"],
    ["entender","comprendre"],
    [["tomar","coger"],"prendre"],
    ["dar","donner"],
    ["ir","aller"],
    ["irse","s'en aller"],
    ["llevar",["porter","emporter","mener","emmener"]],
    ["llevarse","emporter avec soi"],
    ["traer","apporter"],
    ["poner",["mettre","poser"]],
    ["meter","mettre dans"],
    ["saber","savoir"],
    ["quedar","rester"],
    ["gustar",["plaire","aimer"]],
    ["dejar",["laisser","quitter"]],
    ["conocer","connaitre"],
    ["empezar","commencer"],
    ["seguir",["suivre","continuer"]],
    ["cruzar","traverser"],
    ["buscar","chercher"],
    ["encontrar",["trouver","rencontrer"]],
    ["sentir","ressentir"],
    ["sentarse","s'asseoir"],
    ["levantarse","se lever"],
    ["abrir","ouvrir"],
    ["cerrar","fermer"],
    ["guardar",["guarder","ranger"]],
    ["olvidar","oublier"],
    ["recordar",["rappeler","se rappeler"]],
    ["acordarse de","se souvenir de"],
    [["elegir","escoger"],"choisir"],
    ["ayudar","aider"],
    ["divertirse","s'amuser"],
    ["descansar","se reposer"],
    ["dormir","dormir"],
    ["llegar","arriver"],
    ["salir",["partir","sortir"]],
    ["sacar",["sortir","tirer","retirer"]],
    ["volver","revenir"],
    [["ponerse","hacerse","volverse"],"devenir"],
    ["llorar","pleurer"],
    ["bajar","descendre"],
    ["subir","monter"],
    ["sufrir",["subir","souffrir"]],
    ["mostrar","montrer"],
    ["enseñar",["montrer","apprendre à"]],
    ["aprender","apprendre"],
    ["creer","croire"],
    ["crear","créer"],
    ["necesitar","avoir besoin"],
    ["venir","venir"],
    ["parecer",["sembler","paraitre"]],
    ["parecerse a","ressembler à"],
    [["andar","caminar"],"marcher"],
    ["correr","courir"],
    ["occurir","se passer"],
    [["deber","tener que"],"devoir"],
    ["caer","tomber"],
    ["llover","pleuvoir"],
    ["desear",["désirer","souhaiter"]],
    ["esperar",["attendre","espérer"]],
    [["mandar","enviar"],"envoyer"],
    ["ordenar",["ordonner","ranger"]],
    ["gritar","crier"],
    ["callarse","se taire"],
    ["alegrarse","se réjouir"],
    ["cantar","chanter"],
    ["bailar","danser"],
    ["reir","rire"],
    ["sonreir","sourire"],
    ["burlarse","se moquer"],
    ["comprar","acheter"],
    ["vender","vendre"],
    ["ganar","gagner"],
    ["costar","couter"],
    ["cambiar","changer"],
    ["romper",["rompre","casser"]],
    ["mover","bouger"],
    ["moverse","se bouger"],
    ["encender","allumer"],
    ["apagar","éteindre"]
];