
var nom="Espagnol chap 1";
var description="";

//í á ñ À

var quiz=[
    ["Un cartel","une affiche"],
    ["Primer plano","Premier plan"],
    ["Una mujer","Une femme"],
    ["Un bolso","Un sac"],
    ["Varias","Plusieurs"],
    ["Correr","Courir"],
    ["Detrás","Derrière"],
    ["Película","Le film"],
    ["Un tren","Un train"],
    ["A toda velocidad","À toute vitesse"],
    ["Dar","Donner"],
    ["Inmovilidad","Immobilité"],
    ["Comida","Nourriture"],
    ["Contrastar","Contraster"],
    ["Acto generoso","Acte généreux"],
    ["Desesperado","Désespéré"],
    ["Ilusorio","Illusoire"],
    ["Tomar","Prendre"],
    ["Mercancías","Marchandises"],
    ["Migrantes","Migrants"],
    ["Inmigrantes","Immigrants"],
    ["Atravesar","Traverser"],
    ["Llegar","Arriver"],
    ["Estados Unidos","États Unis"],
    ["A fin de","Dans le but de"],
    ["Morir","Mourir"],
    ["Durante","Pendant"],
    ["Trayecto","Trajet"],
    ["Peligroso","Dangereux"],
    ["Viaje","Voyage"],
    ["Ayudar","Aider"],
    ["Echar","Jeter"],
    ["Lanzar","Lancer"],
    ["Albergue","Auberge"],
    ["Compartir","Partager"],
    ["Lograr","Réussir"],
    ["Salvar","Sauver"],
    ["Valiente","Courageux"],
    ["Sencillo","Simple"],
    ["Dedicar","Consacrer"],
    ["Dedicado","Dévoué"],
    ["Necesitado","Dans le besoin"],
    ["No faltar nada","Ne rien manquer"],
    ["Velar en","Veiller sur"],
    ["Pienso que","Je pense que"],
    ["Para mí","Pour moi"],
    ["En mi opinión","À mon avis"],
    ["Según yo","Selon moi"],
    ["Aunque","Même si"],
    ["Ya que","Car"],
    ["Porque","Parce que"],
    ["Animar","Encourager"],
    ["Verdad","Vérité"],
    ["Sobre","Sur"],
    ["Encima de","Au dessus"],
    ["Abajo","En dessous"],
    ["Subir","Monter"],
    ["Heroína","Héroïne"],
    ["Correr un riesgo","Courir un risque"],
    ["Caerse","Tomber"],
    ["Huir","Fuir"],
    ["Entender","Comprendre"],
    ["Medio millón","Demi million"],
    ["El sueño americano","Le rêve américain"],
    ["Tratar de","Essayer de"],
    ["Conseguir","Obtenir"],
    ["Emigrantes","Émigrants"],
    ["Salir","Sortir"],
    ["Buscar","Chercher"],
    ["Ir","Aller"],
    ["Quedar","Rester"],
    ["Volver","Revenir"],
    ["Pasar","Passer"],
    ["Pasear","Se promener"],
    ["Peor","Pire"],
    ["Escapar","Échapper"],
    ["Pobreza","Pauvreté"],
    ["Discrimination","Discriminación"],
    ["Un río","Un fleuve"],
    ["Alejarse","S'éloigner"],
    ["Acercarse","Se rapprocher"],
    ["Un fresco","Une fresque"],
    ["Pintar","Peindre"],
    ["Una caricatura","Une caricature"],
    ["Vias ferreas","Voies férrées"],
    ["El techo","Le toit"],
    ["Viajeros","Voyageurs"],
    ["Juguete infantil","Jouet d'enfant"],
    ["Un monstruo","Un monstre"],
    ["Un desierto","Un désert"],
    ["Una cabeza de piedra","Une tête de pierre"],
    ["Un cuerpo","Un corps"],
    ["Estar sentado","Être assis"],
    ["Acordarse","Se souvenir"],
    ["Recordar","Rappeler"],
    ["Viaje sin fin","Voyage sans fin"],
    ["En efecto","En effet"],
    ["Querer","Vouloir"],
    ["Miedo","Peur"],
    ["Prácticas inhumanas","Pratiques inhumaines"],
    ["Reaccionar","Réagir"],
    ["Malestar","Mal-être"],
    ["Pesado","Pesant"],
    ["Salvaje","Sauvage"],
];