var quiz=[
    ["Bring up","évoquer"],
    ["Bring it on!","Vas-y!"],
    ["Call on","Faire appel à"],
    ["Call off","Annuler"],
    ["Cheer up","retrouver le sourire"],
    ["Come up","Se présenter"],
    ["Come in","Entrer"],
    ["Come across","rencontrer par hasard"],
    ["Cut off","Couper les liens"],
    ["Cut in","interrompre"],
    ["Drop by/dropt in","passer à l’improviste"],
    ["Drop off","Déposer"],
    ["Fall apart","s’effrondrer"],
    ["Fall down","tomber"],
    ["Fall behind","Prendre du retard"],
    ["Fill in","Compléter"],
    ["Fill up","Remplir"],
    ["Get away","S’enfuir"],
];
/*
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""],
    ["",""]
];

//0=question 1=réponse
*/