var quiz=[
    ["Bring up","évoquer"],
    ["Bring it on!","Vas-y!"],
    ["Call on","Faire appel à"],
    ["Call off","Annuler"],
    ["Cheer up","retrouver le sourire"],
    ["Come up","Se présenter"],
    ["Come in","Entrer"],
    ["Come across","rencontrer par hasard"],
    ["Cut off","Couper les liens"],
    ["Cut in","interrompre"],
    ["Drop by/dropt in","passer à l’improviste"],
    ["Drop off","Déposer"],
    ["Fall apart","s’effrondrer"],
    ["Fall down","tomber"],
    ["Fall behind","Prendre du retard"],
    ["Fill in","Compléter"],
    ["Fill up","Remplir"],
    ["Get away","S’enfuir"],
    ["Get around","se déplacer"],
    ["Get along","se débrouiller"],
    ["Get up","Se lever"],
    ["Get back to","Reprendre"],
    ["Get back at","Se venger"],
    ["Give in","céder"],
    ["Give away","Faire don de"],
    ["Give up","Abandonner"],
    ["Go out","Sortir"],
    ["Go ahead","Y aller"],
    ["Grow up","Grandir"],
    ["Grow apart","Se perdre de vue"],
    ["Hang on","rester"],
    ["Hang out","Traîner"],
    ["Hang up","Raccrocher"],
    ["Hold on","Tenir bon"],
    ["Hold back","Retenir"],
    ["Log in","Se connecter"],
    ["Log out","Se déconnecter"],
    ["Pay back","Rembourser"],
    ["Pay for","Payer pour"],
    ["Put out","Éteindre"],
    ["Put on","Mettre"],
    ["Take off","Enlever"],
    ["Take out","Sortir quelqu’un"],
    ["Turn on","Allumer, ouvrir"],
    ["Turn off","Fermer, éteindre"],
    ["Turn around","se retourner"],
    ["Turn up","venir"],
    ["Work out","Faire du sport"],
];

//0=question 1=réponse